name: XSEvent
version: '1.0-SNAPSHOT'
main: net.xsapi.panat.xsevent.core.core
api-version: 1.19
authors: [ PanatXsectorZ ]
softdepend: [CustomFishing]
description: Make your player have a task event!
commands:
  xsevent:
    description: command for xsevent plugin
    aliases:
      - event